global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "subspace"
    scrape_interval: 5s
    static_configs:
      - targets: ["subspace-node:9615"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]