apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    isDefault: true
    access: proxy
    orgId: 1
    url: http://prometheus:9090/
    version: 1
    editable: true
    jsonData:
      timeInterval: 15s
