{
 "title": "Subspace Dashboard",
 "description": "Monitor the health and progress of your Subspace node",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle'}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5) / count(count(node_cpu_seconds_total) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15) /  count(count(node_cpu_seconds_total) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_SwapTotal_bytes" }
   ]
  },
  { "title": "Validator Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Sync Target",
   "type": "stat",
   "description": "Target Substrate blockheight",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"sync_target\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Finalized",
   "type": "stat",
   "description": "Finalized Substrate blockheight",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"finalized\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncing Peers",
   "type": "stat",
   "description": "Number of syncing Substrate peers",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "substrate_sync_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peer Set",
   "type": "stat",
   "description": "Discovered Substrate peerset size",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peerset_num_discovered"
    }
   ]
  },
  {
   "title": "Incoming / Sec",
   "type": "stat",
   "description": "Incoming Substrate connections over the last 30s",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_incoming_connections_total[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks Constructed",
   "type": "stat",
   "description": "Total number of blocks constructed",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_block_constructed_sum"
    }
   ]
  },
  {
   "title": "Block Proposal Time",
   "type": "stat",
   "description": "Time taken to propose a block",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(substrate_proposer_block_proposal_time_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create Inherents",
   "type": "stat",
   "description": "Total inhererents created",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_create_inherents_time_count"
    }
   ]
  },
  {
   "title": "SYNC_TXNS [Count]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(substrate_sync_propagated_transactions[1m])"
    }
   ]
  },
  {
   "title": "BLOCK_VERIFICATION & IMPORT_TIME [Sec]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "rate(substrate_block_verification_and_import_time_bucket[1m])"
    }
   ]
  },
  {
   "title": "VALIDATION_FINISHED [Count]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "rate(substrate_sub_txpool_validations_finished[1m])"
    }
   ]
  },
  {
   "title": "INCOMING_REQ_SUCCESS [Bucket]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_requests_in_success_total_bucket[1m])"
    }
   ]
  },
  {
   "title": "OUTGOING_REQ_SUCCESS [Bucket]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_requests_out_success_total_bucket[1m])"
    }
   ]
  },
  {
   "title": "POLLING_DURATION [Bucket]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_duration_bucket[1m])"
    }
   ]
  },
  {
   "title": "NETWORK_IN & OUT [MBytes]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_network_bytes_total[1m]) / 1000000"
    }
   ]
  },
  {
   "title": "INCOMING_HANDSHAKE_ERRORS [Count]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_incoming_connections_handshake_errors_total"
    }
   ]
  },
  {
   "title": "TOKIO_THREADS [Count]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "targets": [
    { "expr": "substrate_tokio_threads_total" }
   ]
  },
  { "title": "Sync Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Syncronisation Progress",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "substrate_block_height", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Sync Target",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"sync_target\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Best",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "RAM Total" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes",
     "legendFormat": "RAM Cache + Buffer"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "RAM Free" },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user'}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait'}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle'}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "percentunit", "label": "%util" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total [$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}